name: Upload TestFlight

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.3.app/Contents/Developer'
      
    - name: Show Xcode version
      run: xcodebuild -version
  
    - name: Bundle Install
      run: bundle install
       
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
          
    - name: Pod Install
      if: steps.cache-cocoapods.outputs.cache-hit != 'true'
      run: pod install
      
    - name: Upload a new build to App Store Connect
      env:
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        PERSONAL_GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}
      run: bundle exec fastlane beta